Repository ory/docs, pull requests merged in 2025-03, with the labels that each got.

#2045 feat: restructure docs navigation
  docs/guides/authentication.mdx
  docs/quickstart/sdks.mdx
  docusaurus.config.ts
  src/navbar.ts
  src/sidebar.ts
  vercel.json
Labels: feat

#2049 docs: update node express quickstart
  code-examples/protect-page-login/expressjs/README.md
  code-examples/protect-page-login/expressjs/app.js
  code-examples/protect-page-login/expressjs/bin/www
  code-examples/protect-page-login/expressjs/index.js
  code-examples/protect-page-login/expressjs/package-lock.json
  code-examples/protect-page-login/expressjs/package.json
  code-examples/protect-page-login/expressjs/public/stylesheets/style.css
  code-examples/protect-page-login/expressjs/routes/index.js
  code-examples/protect-page-login/expressjs/views/error.jade
  code-examples/protect-page-login/expressjs/views/index.jade
  code-examples/protect-page-login/expressjs/views/layout.jade
  docs/getting-started/_common/create-project.mdx
  docs/getting-started/_static/shared/project-credentials.png
  docs/getting-started/_static/shared/project-settings-tab.png
  docs/getting-started/integrate-auth/10_expressjs.mdx
Labels: area/docs

#2060 docs: add ota for response code
  docs/troubleshooting/50_account-linking-response-code.mdx
Labels: Needs Triage

#2063 chore: update technical advisory text
  docs/troubleshooting/50_account-linking-response-code.mdx
Labels: Needs Triage

#2051 docs: add Ory OEL to nav
  src/navbar.ts
  src/sidebar.ts
Labels: area/docs
